#![forbid(unsafe_code)]
#![warn(clippy::all, clippy::pedantic)]

use std::cmp::Ordering;

const DEFAULT_LIMIT: usize = 5;
const MAX_LIMIT: usize = 50;

/// Returns the stable identifier for the retrieve crate.
#[must_use]
pub const fn crate_name() -> &'static str {
    "youaskm3-knowledge-retrieve"
}

/// Prepared document supplied by the Traverse host from the generated artifact index.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RetrieveDocument {
    /// Stable artifact id from the generated search index.
    pub artifact_id: String,
    /// Human-readable artifact title.
    pub title: String,
    /// Source path preserved for grounding and citations.
    pub source_path: String,
    /// Searchable source excerpt.
    pub excerpt: String,
}

/// Contract-shaped retrieval input.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RetrieveInput {
    /// User question.
    pub query: String,
    /// Artifact index path supplied by the workflow. The pure runtime does not read it.
    pub artifact_index_path: String,
    /// Optional result limit. Defaults to five.
    pub limit: Option<usize>,
    /// Trace id generated by the Traverse workflow.
    pub trace_id: String,
}

/// Ranked source-aware retrieval result.
#[derive(Debug, Clone, PartialEq)]
pub struct RetrieveResult {
    /// Stable artifact id.
    pub artifact_id: String,
    /// Deterministic source chunk id derived from the artifact id.
    pub chunk_id: String,
    /// Human-readable artifact title.
    pub title: String,
    /// Source path preserved for grounding and citations.
    pub source_path: String,
    /// Searchable source excerpt.
    pub excerpt: String,
    /// Deterministic relevance score.
    pub score: f32,
    /// Human-readable score evidence.
    pub score_basis: Vec<String>,
}

/// Contract-shaped retrieval output.
#[derive(Debug, Clone, PartialEq)]
pub struct RetrieveOutput {
    /// Ranked retrieval results.
    pub results: Vec<RetrieveResult>,
    /// Trace id copied from the Traverse workflow.
    pub trace_id: String,
}

/// Errors returned when retrieval input is invalid.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RetrieveError {
    /// Query was empty after trimming.
    MissingQuery,
    /// Artifact index path was empty after trimming.
    MissingArtifactIndexPath,
    /// Trace id was empty after trimming.
    MissingTraceId,
    /// Limit was zero or above the MVP maximum.
    InvalidLimit,
}

impl std::fmt::Display for RetrieveError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingQuery => f.write_str("missing retrieval query"),
            Self::MissingArtifactIndexPath => f.write_str("missing artifact index path"),
            Self::MissingTraceId => f.write_str("missing trace id"),
            Self::InvalidLimit => f.write_str("retrieval limit must be between 1 and 50"),
        }
    }
}

/// Retrieves ranked source chunks without filesystem, network, or environment access.
///
/// # Errors
///
/// Returns an error when required contract fields are missing or the requested
/// limit is outside the first-MVP bounds.
pub fn retrieve(
    input: &RetrieveInput,
    documents: &[RetrieveDocument],
) -> Result<RetrieveOutput, RetrieveError> {
    let query_terms = normalize_query(&input.query)?;
    let artifact_index_path = input.artifact_index_path.trim();
    if artifact_index_path.is_empty() {
        return Err(RetrieveError::MissingArtifactIndexPath);
    }

    let trace_id = input.trace_id.trim();
    if trace_id.is_empty() {
        return Err(RetrieveError::MissingTraceId);
    }

    let limit = normalize_limit(input.limit)?;
    let mut results = documents
        .iter()
        .filter_map(|document| score_document(document, &query_terms))
        .collect::<Vec<_>>();

    results.sort_by(compare_results);
    results.truncate(limit);

    Ok(RetrieveOutput {
        results,
        trace_id: trace_id.to_string(),
    })
}

fn normalize_query(query: &str) -> Result<Vec<String>, RetrieveError> {
    let terms = query
        .split_whitespace()
        .map(|term| term.trim().to_ascii_lowercase())
        .filter(|term| !term.is_empty())
        .collect::<Vec<_>>();

    if terms.is_empty() {
        return Err(RetrieveError::MissingQuery);
    }

    Ok(terms)
}

fn normalize_limit(limit: Option<usize>) -> Result<usize, RetrieveError> {
    match limit {
        Some(0) => Err(RetrieveError::InvalidLimit),
        Some(value) if value > MAX_LIMIT => Err(RetrieveError::InvalidLimit),
        Some(value) => Ok(value),
        None => Ok(DEFAULT_LIMIT),
    }
}

fn score_document(document: &RetrieveDocument, query_terms: &[String]) -> Option<RetrieveResult> {
    let title = document.title.to_ascii_lowercase();
    let excerpt = document.excerpt.to_ascii_lowercase();
    let source_path = document.source_path.to_ascii_lowercase();
    let mut score = 0.0_f32;
    let mut score_basis = Vec::new();

    for term in query_terms {
        if title.contains(term) {
            score += 3.0;
            score_basis.push(format!("title:{term}"));
        }

        if excerpt.contains(term) {
            score += 1.0;
            score_basis.push(format!("excerpt:{term}"));
        }

        if source_path.contains(term) {
            score += 0.5;
            score_basis.push(format!("source_path:{term}"));
        }
    }

    if score <= 0.0 {
        return None;
    }

    Some(RetrieveResult {
        artifact_id: document.artifact_id.clone(),
        chunk_id: chunk_id_for_artifact(&document.artifact_id),
        title: document.title.clone(),
        source_path: document.source_path.clone(),
        excerpt: document.excerpt.clone(),
        score,
        score_basis,
    })
}

fn chunk_id_for_artifact(artifact_id: &str) -> String {
    format!("{artifact_id}:chunk:0")
}

fn compare_results(left: &RetrieveResult, right: &RetrieveResult) -> Ordering {
    right
        .score
        .total_cmp(&left.score)
        .then_with(|| left.title.cmp(&right.title))
        .then_with(|| left.artifact_id.cmp(&right.artifact_id))
}

#[cfg(test)]
mod tests {
    use super::{
        RetrieveDocument, RetrieveError, RetrieveInput, RetrieveResult, compare_results,
        crate_name, retrieve,
    };
    use std::cmp::Ordering;

    fn input(query: &str) -> RetrieveInput {
        RetrieveInput {
            query: query.to_string(),
            artifact_index_path: "app/site/search-index.json".to_string(),
            limit: None,
            trace_id: "trace-1".to_string(),
        }
    }

    fn document(
        artifact_id: &str,
        title: &str,
        excerpt: &str,
        source_path: &str,
    ) -> RetrieveDocument {
        RetrieveDocument {
            artifact_id: artifact_id.to_string(),
            title: title.to_string(),
            source_path: source_path.to_string(),
            excerpt: excerpt.to_string(),
        }
    }

    #[test]
    fn crate_name_matches_package() {
        assert_eq!(crate_name(), "youaskm3-knowledge-retrieve");
    }

    #[test]
    fn rejects_missing_query() {
        assert_eq!(
            retrieve(&input("   "), &[]),
            Err(RetrieveError::MissingQuery)
        );
        assert_eq!(
            RetrieveError::MissingQuery.to_string(),
            "missing retrieval query"
        );
    }

    #[test]
    fn rejects_missing_artifact_index_path() {
        let mut input = input("source");
        input.artifact_index_path = " ".to_string();

        assert_eq!(
            retrieve(&input, &[]),
            Err(RetrieveError::MissingArtifactIndexPath)
        );
        assert_eq!(
            RetrieveError::MissingArtifactIndexPath.to_string(),
            "missing artifact index path"
        );
    }

    #[test]
    fn rejects_missing_trace_id() {
        let mut input = input("source");
        input.trace_id = " ".to_string();

        assert_eq!(retrieve(&input, &[]), Err(RetrieveError::MissingTraceId));
        assert_eq!(
            RetrieveError::MissingTraceId.to_string(),
            "missing trace id"
        );
    }

    #[test]
    fn rejects_invalid_limits() {
        let mut zero = input("source");
        zero.limit = Some(0);
        let mut too_large = input("source");
        too_large.limit = Some(51);

        assert_eq!(retrieve(&zero, &[]), Err(RetrieveError::InvalidLimit));
        assert_eq!(retrieve(&too_large, &[]), Err(RetrieveError::InvalidLimit));
        assert_eq!(
            RetrieveError::InvalidLimit.to_string(),
            "retrieval limit must be between 1 and 50"
        );
    }

    #[test]
    fn returns_source_attributed_ranked_results() -> Result<(), RetrieveError> {
        let documents = vec![
            document(
                "artifact-excerpt",
                "Architecture Notes",
                "Source grounding appears in the excerpt.",
                "knowledge/blog/architecture.md",
            ),
            document(
                "artifact-title",
                "Source Grounding",
                "General notes about citations.",
                "knowledge/blog/source-grounding.md",
            ),
            document(
                "artifact-other",
                "Unrelated",
                "No matching terms here.",
                "knowledge/blog/other.md",
            ),
        ];

        let output = retrieve(&input("source grounding"), &documents)?;

        assert_eq!(output.trace_id, "trace-1");
        assert_eq!(output.results.len(), 2);
        assert_eq!(output.results[0].artifact_id, "artifact-title");
        assert_eq!(output.results[0].chunk_id, "artifact-title:chunk:0");
        assert_eq!(
            output.results[0].source_path,
            "knowledge/blog/source-grounding.md"
        );
        assert!(output.results[0].score > output.results[1].score);
        assert_eq!(
            output.results[0].score_basis,
            vec![
                "title:source",
                "source_path:source",
                "title:grounding",
                "source_path:grounding"
            ]
        );

        Ok(())
    }

    #[test]
    fn returns_empty_results_when_no_documents_match() -> Result<(), RetrieveError> {
        let documents = vec![document(
            "artifact-other",
            "Unrelated",
            "No matching terms here.",
            "knowledge/blog/other.md",
        )];

        let output = retrieve(&input("portable"), &documents)?;

        assert!(output.results.is_empty());

        Ok(())
    }

    #[test]
    fn applies_explicit_limit() -> Result<(), RetrieveError> {
        let mut input = input("source");
        input.limit = Some(1);
        let documents = vec![
            document(
                "artifact-a",
                "Source A",
                "source excerpt",
                "knowledge/blog/a.md",
            ),
            document(
                "artifact-b",
                "Source B",
                "source excerpt",
                "knowledge/blog/b.md",
            ),
        ];

        let output = retrieve(&input, &documents)?;

        assert_eq!(output.results.len(), 1);

        Ok(())
    }

    #[test]
    fn compare_results_breaks_ties_by_title_then_artifact_id() {
        let left = RetrieveResult {
            artifact_id: "a".to_string(),
            chunk_id: "a:chunk:0".to_string(),
            title: "Alpha".to_string(),
            source_path: "knowledge/a.md".to_string(),
            excerpt: "source".to_string(),
            score: 3.0,
            score_basis: vec!["title:source".to_string()],
        };
        let right = RetrieveResult {
            artifact_id: "b".to_string(),
            chunk_id: "b:chunk:0".to_string(),
            title: "Beta".to_string(),
            source_path: "knowledge/b.md".to_string(),
            excerpt: "source".to_string(),
            score: 3.0,
            score_basis: vec!["title:source".to_string()],
        };

        assert_eq!(compare_results(&left, &right), Ordering::Less);

        let same_title = RetrieveResult {
            artifact_id: "b".to_string(),
            chunk_id: "b:chunk:0".to_string(),
            title: "Alpha".to_string(),
            source_path: "knowledge/b.md".to_string(),
            excerpt: "source".to_string(),
            score: 3.0,
            score_basis: vec!["title:source".to_string()],
        };

        assert_eq!(compare_results(&left, &same_title), Ordering::Less);
    }
}
