#![forbid(unsafe_code)]
#![warn(clippy::all, clippy::pedantic)]

use std::collections::{BTreeMap, BTreeSet};

/// Returns the stable identifier for the answer validation crate.
#[must_use]
pub const fn crate_name() -> &'static str {
    "youaskm3-knowledge-answer-validate"
}

/// Source citation supplied by inference or answer composition.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AnswerCitation {
    /// Stable citation id shown in the answer.
    pub citation_id: String,
    /// Stable source artifact id.
    pub artifact_id: String,
    /// Stable source chunk id.
    pub chunk_id: String,
    /// Source path for traceability.
    pub source_path: String,
    /// Excerpt used by downstream formatting.
    pub excerpt: String,
}

/// Retrieved chunk available for citation validation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RetrievedChunk {
    /// Stable source artifact id.
    pub artifact_id: String,
    /// Stable source chunk id.
    pub chunk_id: String,
    /// Source path for traceability.
    pub source_path: String,
    /// Retrieved text excerpt.
    pub excerpt: String,
}

/// Graph evidence available for citation validation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GraphEvidence {
    /// Graph node ids included in the answer context.
    pub node_ids: Vec<String>,
    /// Graph edge ids included in the answer context.
    pub edge_ids: Vec<String>,
    /// Source chunk ids supporting the graph evidence.
    pub supporting_chunk_ids: Vec<String>,
}

/// Contract-shaped answer validation input.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AnswerValidateInput {
    /// Answer text to validate.
    pub answer: String,
    /// Citations claimed by the answer.
    pub citations: Vec<AnswerCitation>,
    /// Retrieved chunks available as source evidence.
    pub retrieved_chunks: Vec<RetrievedChunk>,
    /// Graph evidence available as source evidence.
    pub graph_evidence: Vec<GraphEvidence>,
    /// Trace id generated by the Traverse workflow.
    pub trace_id: String,
}

/// Overall validation status.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ValidationStatus {
    /// All required checks passed.
    Valid,
    /// Required checks passed with warnings.
    Partial,
    /// One or more required checks failed.
    Invalid,
}

/// Individual validation check status.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CheckStatus {
    /// Check passed.
    Pass,
    /// Check failed.
    Fail,
    /// Check produced a warning.
    Warn,
}

/// Contract-shaped validation check.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ValidationCheck {
    /// Stable check name.
    pub name: String,
    /// Check status.
    pub status: CheckStatus,
    /// Human-readable validation detail.
    pub message: String,
}

/// Contract-shaped answer validation output.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AnswerValidateOutput {
    /// Overall validation status.
    pub status: ValidationStatus,
    /// Ordered validation checks.
    pub checks: Vec<ValidationCheck>,
    /// Trace id copied from the Traverse workflow.
    pub trace_id: String,
}

/// Errors returned when validation input cannot produce a traceable result.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AnswerValidateError {
    /// Trace id was empty after trimming.
    MissingTraceId,
}

impl std::fmt::Display for AnswerValidateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingTraceId => f.write_str("missing trace id"),
        }
    }
}

impl std::error::Error for AnswerValidateError {}

/// Validates answer citations against retrieved chunks and graph evidence.
///
/// # Errors
///
/// Returns an error when trace id is missing.
pub fn validate_answer(
    input: &AnswerValidateInput,
) -> Result<AnswerValidateOutput, AnswerValidateError> {
    let trace_id = input.trace_id.trim().to_string();
    if trace_id.is_empty() {
        return Err(AnswerValidateError::MissingTraceId);
    }

    let available_sources = available_sources(&input.retrieved_chunks);
    let citation_refs = citation_refs(&input.citations);
    let duplicate_ids = duplicate_citation_ids(&input.citations);
    let unsupported_refs = unsupported_citation_refs(&citation_refs, &available_sources);
    let checks = vec![
        answer_present_check(&input.answer),
        citations_present_check(&citation_refs),
        citations_supported_check(&unsupported_refs),
        duplicate_citations_check(&duplicate_ids),
    ];

    Ok(AnswerValidateOutput {
        status: overall_status(&checks),
        checks,
        trace_id,
    })
}

fn answer_present_check(answer: &str) -> ValidationCheck {
    if normalize_text(answer).is_empty() {
        return check("answer-present", CheckStatus::Fail, "answer text is empty");
    }

    check(
        "answer-present",
        CheckStatus::Pass,
        "answer text is present",
    )
}

fn citations_present_check(citation_refs: &BTreeSet<SourceRef>) -> ValidationCheck {
    if citation_refs.is_empty() {
        return check(
            "citations-present",
            CheckStatus::Fail,
            "answer has no source-backed citations",
        );
    }

    check(
        "citations-present",
        CheckStatus::Pass,
        "answer includes source-backed citations",
    )
}

fn citations_supported_check(unsupported_refs: &BTreeSet<SourceRef>) -> ValidationCheck {
    if unsupported_refs.is_empty() {
        return check(
            "citations-supported",
            CheckStatus::Pass,
            "all citations map to available source evidence",
        );
    }

    check(
        "citations-supported",
        CheckStatus::Fail,
        &format!(
            "unsupported citations: {}",
            refs_to_message(unsupported_refs)
        ),
    )
}

fn duplicate_citations_check(duplicate_ids: &BTreeSet<String>) -> ValidationCheck {
    if duplicate_ids.is_empty() {
        return check(
            "citations-unique",
            CheckStatus::Pass,
            "citation ids are unique",
        );
    }

    check(
        "citations-unique",
        CheckStatus::Warn,
        &format!(
            "duplicate citation ids: {}",
            duplicate_ids.iter().cloned().collect::<Vec<_>>().join(", ")
        ),
    )
}

fn check(name: &str, status: CheckStatus, message: &str) -> ValidationCheck {
    ValidationCheck {
        name: name.to_string(),
        status,
        message: message.to_string(),
    }
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
struct SourceRef {
    artifact_id: String,
    chunk_id: String,
    source_path: String,
}

fn available_sources(chunks: &[RetrievedChunk]) -> BTreeSet<SourceRef> {
    chunks
        .iter()
        .filter(|chunk| !is_blank(&chunk.artifact_id) && !is_blank(&chunk.chunk_id))
        .map(|chunk| SourceRef {
            artifact_id: chunk.artifact_id.trim().to_string(),
            chunk_id: chunk.chunk_id.trim().to_string(),
            source_path: chunk.source_path.trim().to_string(),
        })
        .collect()
}

fn citation_refs(citations: &[AnswerCitation]) -> BTreeSet<SourceRef> {
    citations
        .iter()
        .filter(|citation| !is_blank(&citation.artifact_id) && !is_blank(&citation.chunk_id))
        .map(|citation| SourceRef {
            artifact_id: citation.artifact_id.trim().to_string(),
            chunk_id: citation.chunk_id.trim().to_string(),
            source_path: citation.source_path.trim().to_string(),
        })
        .collect()
}

fn duplicate_citation_ids(citations: &[AnswerCitation]) -> BTreeSet<String> {
    let mut counts = BTreeMap::new();
    for citation in citations {
        let citation_id = citation.citation_id.trim();
        if !citation_id.is_empty() {
            *counts.entry(citation_id.to_string()).or_insert(0_usize) += 1;
        }
    }

    counts
        .into_iter()
        .filter_map(|(citation_id, count)| (count > 1).then_some(citation_id))
        .collect()
}

fn unsupported_citation_refs(
    citation_refs: &BTreeSet<SourceRef>,
    available_sources: &BTreeSet<SourceRef>,
) -> BTreeSet<SourceRef> {
    citation_refs
        .difference(available_sources)
        .cloned()
        .collect::<BTreeSet<_>>()
}

fn refs_to_message(refs: &BTreeSet<SourceRef>) -> String {
    refs.iter()
        .map(|source_ref| {
            format!(
                "{}:{}:{}",
                source_ref.artifact_id, source_ref.chunk_id, source_ref.source_path
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn overall_status(checks: &[ValidationCheck]) -> ValidationStatus {
    if checks.iter().any(|check| check.status == CheckStatus::Fail) {
        return ValidationStatus::Invalid;
    }

    if checks.iter().any(|check| check.status == CheckStatus::Warn) {
        return ValidationStatus::Partial;
    }

    ValidationStatus::Valid
}

fn normalize_text(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn is_blank(value: &str) -> bool {
    value.trim().is_empty()
}

#[cfg(test)]
mod tests {
    use super::{
        AnswerCitation, AnswerValidateError, AnswerValidateInput, CheckStatus, GraphEvidence,
        RetrievedChunk, ValidationCheck, ValidationStatus, crate_name, validate_answer,
    };

    fn citation(id: &str, artifact_id: &str, chunk_id: &str) -> AnswerCitation {
        AnswerCitation {
            citation_id: id.to_string(),
            artifact_id: artifact_id.to_string(),
            chunk_id: chunk_id.to_string(),
            source_path: format!("knowledge/{chunk_id}.md"),
            excerpt: "source excerpt".to_string(),
        }
    }

    fn chunk(artifact_id: &str, chunk_id: &str) -> RetrievedChunk {
        RetrievedChunk {
            artifact_id: artifact_id.to_string(),
            chunk_id: chunk_id.to_string(),
            source_path: format!("knowledge/{chunk_id}.md"),
            excerpt: "retrieved excerpt".to_string(),
        }
    }

    fn graph_evidence(chunk_id: &str) -> GraphEvidence {
        GraphEvidence {
            node_ids: vec!["node-a".to_string()],
            edge_ids: vec!["edge-a".to_string()],
            supporting_chunk_ids: vec![chunk_id.to_string()],
        }
    }

    fn input() -> AnswerValidateInput {
        AnswerValidateInput {
            answer: "A grounded answer [1].".to_string(),
            citations: vec![citation("1", "artifact-a", "chunk-a")],
            retrieved_chunks: vec![chunk("artifact-a", "chunk-a")],
            graph_evidence: Vec::new(),
            trace_id: "trace-validation".to_string(),
        }
    }

    #[test]
    fn crate_name_matches_package() {
        assert_eq!(crate_name(), "youaskm3-knowledge-answer-validate");
    }

    #[test]
    fn validates_supported_citations() -> Result<(), AnswerValidateError> {
        let output = validate_answer(&input())?;

        assert_eq!(output.status, ValidationStatus::Valid);
        assert_eq!(output.trace_id, "trace-validation");
        assert!(
            output
                .checks
                .iter()
                .all(|check| check.status == CheckStatus::Pass)
        );
        Ok(())
    }

    #[test]
    fn fails_missing_citations() -> Result<(), AnswerValidateError> {
        let mut input = input();
        input.citations.clear();

        let output = validate_answer(&input)?;

        assert_eq!(output.status, ValidationStatus::Invalid);
        assert_check(
            &output,
            "citations-present",
            CheckStatus::Fail,
            "answer has no source-backed citations",
        );
        Ok(())
    }

    #[test]
    fn fails_unknown_citations() -> Result<(), AnswerValidateError> {
        let mut input = input();
        input.citations = vec![citation("1", "artifact-z", "chunk-z")];

        let output = validate_answer(&input)?;

        assert_eq!(output.status, ValidationStatus::Invalid);
        assert_check(
            &output,
            "citations-supported",
            CheckStatus::Fail,
            "unsupported citations: artifact-z:chunk-z:knowledge/chunk-z.md",
        );
        Ok(())
    }

    #[test]
    fn warns_on_duplicate_citations() -> Result<(), AnswerValidateError> {
        let mut input = input();
        input.citations = vec![
            citation("1", "artifact-a", "chunk-a"),
            citation("1", "artifact-a", "chunk-a"),
        ];

        let output = validate_answer(&input)?;

        assert_eq!(output.status, ValidationStatus::Partial);
        assert_check(
            &output,
            "citations-unique",
            CheckStatus::Warn,
            "duplicate citation ids: 1",
        );
        Ok(())
    }

    #[test]
    fn fails_empty_answer() -> Result<(), AnswerValidateError> {
        let mut input = input();
        input.answer = " ".to_string();

        let output = validate_answer(&input)?;

        assert_eq!(output.status, ValidationStatus::Invalid);
        assert_check(
            &output,
            "answer-present",
            CheckStatus::Fail,
            "answer text is empty",
        );
        Ok(())
    }

    #[test]
    fn validates_retrieved_citations_when_graph_evidence_is_present()
    -> Result<(), AnswerValidateError> {
        let mut input = input();
        input.retrieved_chunks = vec![
            chunk("artifact-a", "chunk-a"),
            chunk("artifact-b", "chunk-b"),
        ];
        input.citations = vec![citation("1", "artifact-a", "chunk-a")];
        input.graph_evidence = vec![graph_evidence("chunk-b")];

        let output = validate_answer(&input)?;

        assert_eq!(output.status, ValidationStatus::Valid);
        Ok(())
    }

    #[test]
    fn rejects_missing_trace_id() {
        let mut input = input();
        input.trace_id = " ".to_string();

        assert_eq!(
            validate_answer(&input),
            Err(AnswerValidateError::MissingTraceId)
        );
    }

    #[test]
    fn formats_error_messages() {
        assert_eq!(
            AnswerValidateError::MissingTraceId.to_string(),
            "missing trace id"
        );
    }

    fn assert_check(
        output: &super::AnswerValidateOutput,
        name: &str,
        status: CheckStatus,
        message: &str,
    ) {
        let missing = ValidationCheck {
            name: "__missing__".to_string(),
            status: CheckStatus::Fail,
            message: String::new(),
        };
        let check = output
            .checks
            .iter()
            .find(|check| check.name == name)
            .unwrap_or(&missing);

        assert_ne!(check.name, "__missing__");
        assert_eq!(check.status, status);
        assert_eq!(check.message, message);
    }
}
