#![forbid(unsafe_code)]
#![warn(clippy::all, clippy::pedantic)]

const DEFAULT_MAX_OUTPUT_TOKENS: usize = 1024;
const MAX_OUTPUT_TOKENS: usize = 8192;

/// Returns the stable identifier for the infer crate.
#[must_use]
pub const fn crate_name() -> &'static str {
    "youaskm3-knowledge-infer"
}

/// Placement selected by Traverse for model-backed inference.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InferencePlacement {
    /// Local runtime placement.
    Local,
    /// Server runtime placement.
    Server,
}

/// Contract-shaped inference input.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InferInput {
    /// Prompt generated by the Traverse workflow.
    pub prompt: String,
    /// Packed source and graph context.
    pub context: String,
    /// Optional maximum output token budget.
    pub max_output_tokens: Option<usize>,
    /// Traverse-selected inference capability id.
    pub selected_inference_capability: String,
    /// Traverse-selected placement.
    pub placement: InferencePlacement,
    /// Trace id generated by the Traverse workflow.
    pub trace_id: String,
}

/// Contract-shaped inference output.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InferOutput {
    /// Generated answer text supplied by the Traverse-selected model capability.
    pub text: String,
    /// Traverse-selected inference capability id.
    pub selected_inference_capability: String,
    /// Traverse-selected placement.
    pub placement: InferencePlacement,
    /// Applied maximum output token budget.
    pub max_output_tokens: usize,
    /// Trace id copied from the Traverse workflow.
    pub trace_id: String,
}

/// Errors returned when inference input cannot be executed by a governed host.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InferError {
    /// Prompt was empty after trimming.
    MissingPrompt,
    /// Context was empty after trimming.
    MissingContext,
    /// Traverse did not select a model capability.
    MissingSelectedInferenceCapability,
    /// Trace id was empty after trimming.
    MissingTraceId,
    /// Requested output budget is outside the MVP contract range.
    InvalidMaxOutputTokens,
}

impl std::fmt::Display for InferError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingPrompt => f.write_str("missing inference prompt"),
            Self::MissingContext => f.write_str("missing inference context"),
            Self::MissingSelectedInferenceCapability => {
                f.write_str("missing Traverse-selected inference capability")
            }
            Self::MissingTraceId => f.write_str("missing trace id"),
            Self::InvalidMaxOutputTokens => {
                f.write_str("max output tokens must be between 1 and 8192")
            }
        }
    }
}

impl std::error::Error for InferError {}

/// Validates a Traverse-governed inference request and records host execution evidence.
///
/// The actual model call is owned by the Traverse-selected inference capability.
/// This crate intentionally does not choose a provider, perform network I/O, or
/// synthesize a hidden downstream answer.
///
/// # Errors
///
/// Returns an error when required Traverse-owned input or budget fields are missing.
pub fn record_inference_result(
    input: &InferInput,
    generated_text: &str,
) -> Result<InferOutput, InferError> {
    let prompt = input.prompt.trim();
    if prompt.is_empty() {
        return Err(InferError::MissingPrompt);
    }

    let context = input.context.trim();
    if context.is_empty() {
        return Err(InferError::MissingContext);
    }

    let selected = input.selected_inference_capability.trim();
    if selected.is_empty() {
        return Err(InferError::MissingSelectedInferenceCapability);
    }

    let trace_id = input.trace_id.trim();
    if trace_id.is_empty() {
        return Err(InferError::MissingTraceId);
    }

    let max_output_tokens = normalize_max_output_tokens(input.max_output_tokens)?;

    Ok(InferOutput {
        text: normalize_text(generated_text),
        selected_inference_capability: selected.to_string(),
        placement: input.placement,
        max_output_tokens,
        trace_id: trace_id.to_string(),
    })
}

fn normalize_max_output_tokens(value: Option<usize>) -> Result<usize, InferError> {
    match value {
        Some(0) => Err(InferError::InvalidMaxOutputTokens),
        Some(value) if value > MAX_OUTPUT_TOKENS => Err(InferError::InvalidMaxOutputTokens),
        Some(value) => Ok(value),
        None => Ok(DEFAULT_MAX_OUTPUT_TOKENS),
    }
}

fn normalize_text(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[cfg(test)]
mod tests {
    use super::{InferError, InferInput, InferencePlacement, crate_name, record_inference_result};

    fn input() -> InferInput {
        InferInput {
            prompt: "Answer from the supplied context.".to_string(),
            context: "Source-backed context.".to_string(),
            max_output_tokens: None,
            selected_inference_capability: "traverse.inference.generate".to_string(),
            placement: InferencePlacement::Local,
            trace_id: "trace-1".to_string(),
        }
    }

    #[test]
    fn crate_name_is_stable() {
        assert_eq!(crate_name(), "youaskm3-knowledge-infer");
    }

    #[test]
    fn records_traverse_selected_inference_result() -> Result<(), String> {
        let output = record_inference_result(&input(), "Generated\nanswer.")
            .map_err(|error| error.to_string())?;

        assert_eq!(output.text, "Generated answer.");
        assert_eq!(
            output.selected_inference_capability,
            "traverse.inference.generate"
        );
        assert_eq!(output.placement, InferencePlacement::Local);
        assert_eq!(output.max_output_tokens, 1024);
        assert_eq!(output.trace_id, "trace-1");
        Ok(())
    }

    #[test]
    fn preserves_server_placement_and_explicit_budget() -> Result<(), String> {
        let mut input = input();
        input.placement = InferencePlacement::Server;
        input.max_output_tokens = Some(256);

        let output =
            record_inference_result(&input, "answer").map_err(|error| error.to_string())?;

        assert_eq!(output.placement, InferencePlacement::Server);
        assert_eq!(output.max_output_tokens, 256);
        Ok(())
    }

    #[test]
    fn rejects_missing_governed_inputs() -> Result<(), String> {
        let mut missing_prompt = input();
        missing_prompt.prompt.clear();
        assert_eq!(
            inference_error(record_inference_result(&missing_prompt, "answer"))?,
            InferError::MissingPrompt
        );

        let mut missing_context = input();
        missing_context.context.clear();
        assert_eq!(
            inference_error(record_inference_result(&missing_context, "answer"))?,
            InferError::MissingContext
        );

        let mut missing_selected = input();
        missing_selected.selected_inference_capability.clear();
        assert_eq!(
            inference_error(record_inference_result(&missing_selected, "answer"))?,
            InferError::MissingSelectedInferenceCapability
        );

        let mut missing_trace = input();
        missing_trace.trace_id.clear();
        assert_eq!(
            inference_error(record_inference_result(&missing_trace, "answer"))?,
            InferError::MissingTraceId
        );
        Ok(())
    }

    #[test]
    fn rejects_invalid_output_budget() -> Result<(), String> {
        let mut input = input();
        input.max_output_tokens = Some(0);
        assert_eq!(
            inference_error(record_inference_result(&input, "answer"))?,
            InferError::InvalidMaxOutputTokens
        );

        input.max_output_tokens = Some(8193);
        assert_eq!(
            inference_error(record_inference_result(&input, "answer"))?,
            InferError::InvalidMaxOutputTokens
        );
        Ok(())
    }

    fn inference_error(
        result: Result<super::InferOutput, InferError>,
    ) -> Result<InferError, String> {
        match result {
            Ok(output) => Err(format!("expected inference error, got {output:?}")),
            Err(error) => Ok(error),
        }
    }
}
