#![forbid(unsafe_code)]
#![warn(clippy::all, clippy::pedantic)]

use std::collections::BTreeSet;

const DEFAULT_MAX_HOPS: usize = 1;
const DEFAULT_MAX_EDGES: usize = 25;
const MAX_HOPS: usize = 3;
const MAX_EDGES: usize = 100;

/// Returns the stable identifier for the graph expansion crate.
#[must_use]
pub const fn crate_name() -> &'static str {
    "youaskm3-knowledge-graph-expand"
}

/// Source-backed graph node from the knowledge graph artifact.
#[derive(Debug, Clone, PartialEq)]
pub struct GraphNode {
    /// Stable graph node id.
    pub node_id: String,
    /// Human-readable node label.
    pub label: String,
    /// Node type from the graph artifact.
    pub node_type: String,
    /// Source artifact ids supporting this node.
    pub source_artifact_ids: Vec<String>,
    /// Source chunk ids supporting this node.
    pub source_chunk_ids: Vec<String>,
    /// Source paths supporting this node.
    pub source_paths: Vec<String>,
}

/// Source-backed graph edge from the knowledge graph artifact.
#[derive(Debug, Clone, PartialEq)]
pub struct GraphEdge {
    /// Stable graph edge id.
    pub edge_id: String,
    /// Source node id.
    pub from_node_id: String,
    /// Target node id.
    pub to_node_id: String,
    /// Relationship label.
    pub relationship: String,
    /// Source artifact ids supporting this edge.
    pub source_artifact_ids: Vec<String>,
    /// Source chunk ids supporting this edge.
    pub source_chunk_ids: Vec<String>,
    /// Source paths supporting this edge.
    pub source_paths: Vec<String>,
    /// Extraction method recorded by the graph builder.
    pub extraction_method: String,
    /// Confidence score recorded by the graph builder.
    pub confidence: f32,
}

/// Prepared static graph artifact supplied by the Traverse host.
#[derive(Debug, Clone, PartialEq)]
pub struct KnowledgeGraphArtifact {
    /// Graph artifact schema version.
    pub schema_version: String,
    /// Stable graph id.
    pub graph_id: String,
    /// Source artifact ids used to generate the graph.
    pub generated_from: Vec<String>,
    /// Graph nodes.
    pub nodes: Vec<GraphNode>,
    /// Graph edges.
    pub edges: Vec<GraphEdge>,
}

/// Contract-shaped graph expansion input.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GraphExpandInput {
    /// Graph artifact path supplied by the workflow. The pure runtime does not read it.
    pub graph_path: String,
    /// Retrieved chunk ids used as graph seeds.
    pub seed_chunk_ids: Vec<String>,
    /// Optional hop bound. Defaults to one hop.
    pub max_hops: Option<usize>,
    /// Optional edge bound. Defaults to twenty-five edges.
    pub max_edges: Option<usize>,
    /// Trace id generated by the Traverse workflow.
    pub trace_id: String,
}

/// Stable failure payload for contract-shaped outputs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GraphExpandFailure {
    /// Stable failure code.
    pub code: String,
    /// Human-readable failure message.
    pub message: String,
    /// Whether retrying with different input can recover.
    pub recoverable: bool,
}

/// Contract-shaped graph expansion output.
#[derive(Debug, Clone, PartialEq)]
pub struct GraphExpandOutput {
    /// Bounded graph nodes.
    pub nodes: Vec<GraphNode>,
    /// Bounded graph edges.
    pub edges: Vec<GraphEdge>,
    /// Trace id copied from the Traverse workflow.
    pub trace_id: String,
    /// Optional failure payload for empty or unmatched graph expansion.
    pub failure: Option<GraphExpandFailure>,
}

/// Errors returned when graph expansion input is invalid.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GraphExpandError {
    /// Graph path was empty after trimming.
    MissingGraphPath,
    /// No seed chunk ids were provided.
    MissingSeedChunkIds,
    /// Trace id was empty after trimming.
    MissingTraceId,
    /// Hop bound exceeded the MVP contract.
    InvalidMaxHops,
    /// Edge bound exceeded the MVP contract.
    InvalidMaxEdges,
}

impl std::fmt::Display for GraphExpandError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingGraphPath => f.write_str("missing graph path"),
            Self::MissingSeedChunkIds => f.write_str("missing seed chunk ids"),
            Self::MissingTraceId => f.write_str("missing trace id"),
            Self::InvalidMaxHops => f.write_str("max hops must be between 0 and 3"),
            Self::InvalidMaxEdges => f.write_str("max edges must be between 1 and 100"),
        }
    }
}

impl std::error::Error for GraphExpandError {}

/// Expands source-backed graph context without filesystem, network, or environment access.
///
/// # Errors
///
/// Returns an error when contract-shaped input is invalid.
pub fn expand_graph(
    input: &GraphExpandInput,
    graph: &KnowledgeGraphArtifact,
) -> Result<GraphExpandOutput, GraphExpandError> {
    validate_input(input)?;

    let trace_id = input.trace_id.trim().to_string();
    if graph.nodes.is_empty() && graph.edges.is_empty() {
        return Ok(output_with_failure(
            trace_id,
            "EMPTY_GRAPH",
            "graph artifact has no nodes or edges",
            true,
        ));
    }

    let seed_chunk_ids = normalized_seed_chunk_ids(&input.seed_chunk_ids);
    let max_hops = input.max_hops.unwrap_or(DEFAULT_MAX_HOPS);
    let max_edges = input.max_edges.unwrap_or(DEFAULT_MAX_EDGES);
    let sorted_nodes = sorted_nodes(&graph.nodes);
    let sorted_edges = sorted_edges(&graph.edges);
    let seed_node_ids = seed_node_ids(&sorted_nodes, &seed_chunk_ids);

    if seed_node_ids.is_empty() && !has_seed_edge(&sorted_edges, &seed_chunk_ids) {
        return Ok(output_with_failure(
            trace_id,
            "UNKNOWN_SEED_CHUNK",
            "no graph evidence matched the seed chunk ids",
            true,
        ));
    }

    let included_edge_ids =
        included_edge_ids(&sorted_edges, &seed_chunk_ids, &seed_node_ids, max_hops);
    let mut bounded_edge_ids = included_edge_ids
        .into_iter()
        .take(max_edges)
        .collect::<BTreeSet<_>>();
    let mut included_node_ids = seed_node_ids;

    for edge in &sorted_edges {
        if bounded_edge_ids.contains(edge.edge_id.as_str()) {
            included_node_ids.insert(edge.from_node_id.clone());
            included_node_ids.insert(edge.to_node_id.clone());
        }
    }

    let nodes = sorted_nodes
        .into_iter()
        .filter(|node| included_node_ids.contains(node.node_id.as_str()))
        .cloned()
        .collect::<Vec<_>>();
    let edges = sorted_edges
        .into_iter()
        .filter(|edge| bounded_edge_ids.remove(edge.edge_id.as_str()))
        .cloned()
        .collect::<Vec<_>>();

    Ok(GraphExpandOutput {
        nodes,
        edges,
        trace_id,
        failure: None,
    })
}

fn validate_input(input: &GraphExpandInput) -> Result<(), GraphExpandError> {
    if input.graph_path.trim().is_empty() {
        return Err(GraphExpandError::MissingGraphPath);
    }

    if normalized_seed_chunk_ids(&input.seed_chunk_ids).is_empty() {
        return Err(GraphExpandError::MissingSeedChunkIds);
    }

    if input.trace_id.trim().is_empty() {
        return Err(GraphExpandError::MissingTraceId);
    }

    if input.max_hops.is_some_and(|value| value > MAX_HOPS) {
        return Err(GraphExpandError::InvalidMaxHops);
    }

    if input
        .max_edges
        .is_some_and(|value| value == 0 || value > MAX_EDGES)
    {
        return Err(GraphExpandError::InvalidMaxEdges);
    }

    Ok(())
}

fn output_with_failure(
    trace_id: String,
    code: &str,
    message: &str,
    recoverable: bool,
) -> GraphExpandOutput {
    GraphExpandOutput {
        nodes: Vec::new(),
        edges: Vec::new(),
        trace_id,
        failure: Some(GraphExpandFailure {
            code: code.to_string(),
            message: message.to_string(),
            recoverable,
        }),
    }
}

fn normalized_seed_chunk_ids(seed_chunk_ids: &[String]) -> BTreeSet<String> {
    seed_chunk_ids
        .iter()
        .map(|id| id.trim())
        .filter(|id| !id.is_empty())
        .map(ToString::to_string)
        .collect()
}

fn sorted_nodes(nodes: &[GraphNode]) -> Vec<&GraphNode> {
    let mut sorted = nodes.iter().collect::<Vec<_>>();
    sorted.sort_by(|left, right| left.node_id.cmp(&right.node_id));
    sorted
}

fn sorted_edges(edges: &[GraphEdge]) -> Vec<&GraphEdge> {
    let mut sorted = edges.iter().collect::<Vec<_>>();
    sorted.sort_by(|left, right| left.edge_id.cmp(&right.edge_id));
    sorted
}

fn seed_node_ids(nodes: &[&GraphNode], seed_chunk_ids: &BTreeSet<String>) -> BTreeSet<String> {
    nodes
        .iter()
        .filter(|node| intersects(&node.source_chunk_ids, seed_chunk_ids))
        .map(|node| node.node_id.clone())
        .collect()
}

fn has_seed_edge(edges: &[&GraphEdge], seed_chunk_ids: &BTreeSet<String>) -> bool {
    edges
        .iter()
        .any(|edge| intersects(&edge.source_chunk_ids, seed_chunk_ids))
}

fn included_edge_ids(
    edges: &[&GraphEdge],
    seed_chunk_ids: &BTreeSet<String>,
    seed_node_ids: &BTreeSet<String>,
    max_hops: usize,
) -> BTreeSet<String> {
    let mut included_edge_ids = BTreeSet::new();
    let mut visited_nodes = seed_node_ids.clone();
    let mut frontier = seed_node_ids.clone();

    for edge in edges {
        if intersects(&edge.source_chunk_ids, seed_chunk_ids) {
            included_edge_ids.insert(edge.edge_id.clone());
            visited_nodes.insert(edge.from_node_id.clone());
            visited_nodes.insert(edge.to_node_id.clone());
            frontier.insert(edge.from_node_id.clone());
            frontier.insert(edge.to_node_id.clone());
        }
    }

    for _ in 0..max_hops {
        let mut next_frontier = BTreeSet::new();
        for edge in edges {
            if touches_frontier(edge, &frontier) {
                included_edge_ids.insert(edge.edge_id.clone());
                add_unvisited(&mut visited_nodes, &mut next_frontier, &edge.from_node_id);
                add_unvisited(&mut visited_nodes, &mut next_frontier, &edge.to_node_id);
            }
        }
        if next_frontier.is_empty() {
            break;
        }
        frontier = next_frontier;
    }

    included_edge_ids
}

fn intersects(values: &[String], targets: &BTreeSet<String>) -> bool {
    values.iter().any(|value| targets.contains(value))
}

fn touches_frontier(edge: &GraphEdge, frontier: &BTreeSet<String>) -> bool {
    frontier.contains(&edge.from_node_id) || frontier.contains(&edge.to_node_id)
}

fn add_unvisited(
    visited_nodes: &mut BTreeSet<String>,
    next_frontier: &mut BTreeSet<String>,
    node_id: &str,
) {
    if visited_nodes.insert(node_id.to_string()) {
        next_frontier.insert(node_id.to_string());
    }
}

#[cfg(test)]
mod tests {
    use super::{
        GraphEdge, GraphExpandError, GraphExpandFailure, GraphExpandInput, GraphNode,
        KnowledgeGraphArtifact, crate_name, expand_graph,
    };

    fn node(id: &str, chunk_id: &str) -> GraphNode {
        GraphNode {
            node_id: id.to_string(),
            label: format!("Node {id}"),
            node_type: "concept".to_string(),
            source_artifact_ids: vec![format!("artifact-{chunk_id}")],
            source_chunk_ids: vec![chunk_id.to_string()],
            source_paths: vec![format!("knowledge/{chunk_id}.md")],
        }
    }

    fn edge(id: &str, from: &str, to: &str, chunk_id: &str) -> GraphEdge {
        GraphEdge {
            edge_id: id.to_string(),
            from_node_id: from.to_string(),
            to_node_id: to.to_string(),
            relationship: "supports".to_string(),
            source_artifact_ids: vec![format!("artifact-{chunk_id}")],
            source_chunk_ids: vec![chunk_id.to_string()],
            source_paths: vec![format!("knowledge/{chunk_id}.md")],
            extraction_method: "deterministic-test".to_string(),
            confidence: 0.9,
        }
    }

    fn graph() -> KnowledgeGraphArtifact {
        KnowledgeGraphArtifact {
            schema_version: "0.1.0".to_string(),
            graph_id: "test-graph".to_string(),
            generated_from: vec!["artifact-chunk-a".to_string()],
            nodes: vec![
                node("node-c", "chunk-c"),
                node("node-a", "chunk-a"),
                node("node-b", "chunk-b"),
            ],
            edges: vec![
                edge("edge-b", "node-b", "node-c", "chunk-b"),
                edge("edge-a", "node-a", "node-b", "chunk-a"),
            ],
        }
    }

    fn input() -> GraphExpandInput {
        GraphExpandInput {
            graph_path: "app/site/knowledge-graph.json".to_string(),
            seed_chunk_ids: vec!["chunk-a".to_string()],
            max_hops: Some(1),
            max_edges: Some(10),
            trace_id: "trace-graph".to_string(),
        }
    }

    #[test]
    fn crate_name_matches_package() {
        assert_eq!(crate_name(), "youaskm3-knowledge-graph-expand");
    }

    #[test]
    fn expands_single_hop_from_seed_chunk() -> Result<(), GraphExpandError> {
        let output = expand_graph(&input(), &graph())?;

        assert_eq!(ids(&output.nodes), ["node-a", "node-b", "node-c"]);
        assert_eq!(edge_ids(&output.edges), ["edge-a", "edge-b"]);
        assert_eq!(output.trace_id, "trace-graph");
        assert_eq!(output.failure, None);
        Ok(())
    }

    #[test]
    fn preserves_source_paths_and_evidence_ids() -> Result<(), GraphExpandError> {
        let output = expand_graph(&input(), &graph())?;

        assert_eq!(output.edges[0].source_chunk_ids, ["chunk-a"]);
        assert_eq!(output.edges[0].source_paths, ["knowledge/chunk-a.md"]);
        assert_eq!(output.nodes[0].source_artifact_ids, ["artifact-chunk-a"]);
        Ok(())
    }

    #[test]
    fn output_is_deterministic() -> Result<(), GraphExpandError> {
        let first = expand_graph(&input(), &graph())?;
        let second = expand_graph(&input(), &graph())?;

        assert_eq!(first, second);
        Ok(())
    }

    #[test]
    fn bounds_output_edges() -> Result<(), GraphExpandError> {
        let mut input = input();
        input.max_edges = Some(1);

        let output = expand_graph(&input, &graph())?;

        assert_eq!(edge_ids(&output.edges), ["edge-a"]);
        assert_eq!(ids(&output.nodes), ["node-a", "node-b"]);
        Ok(())
    }

    #[test]
    fn max_zero_hops_keeps_direct_seed_evidence_only() -> Result<(), GraphExpandError> {
        let mut input = input();
        input.max_hops = Some(0);

        let output = expand_graph(&input, &graph())?;

        assert_eq!(edge_ids(&output.edges), ["edge-a"]);
        assert_eq!(ids(&output.nodes), ["node-a", "node-b"]);
        Ok(())
    }

    #[test]
    fn stops_when_no_next_frontier_exists() -> Result<(), GraphExpandError> {
        let graph = KnowledgeGraphArtifact {
            schema_version: "0.1.0".to_string(),
            graph_id: "single-edge".to_string(),
            generated_from: vec!["artifact-chunk-a".to_string()],
            nodes: vec![node("node-a", "chunk-a"), node("node-b", "chunk-b")],
            edges: vec![edge("edge-a", "node-a", "node-b", "chunk-a")],
        };

        let output = expand_graph(&input(), &graph)?;

        assert_eq!(edge_ids(&output.edges), ["edge-a"]);
        assert_eq!(ids(&output.nodes), ["node-a", "node-b"]);
        Ok(())
    }

    #[test]
    fn returns_empty_graph_failure() -> Result<(), GraphExpandError> {
        let graph = KnowledgeGraphArtifact {
            schema_version: "0.1.0".to_string(),
            graph_id: "empty".to_string(),
            generated_from: Vec::new(),
            nodes: Vec::new(),
            edges: Vec::new(),
        };
        let output = expand_graph(&input(), &graph)?;

        assert_eq!(output.nodes, []);
        assert_eq!(output.edges, []);
        assert_eq!(
            output.failure,
            Some(GraphExpandFailure {
                code: "EMPTY_GRAPH".to_string(),
                message: "graph artifact has no nodes or edges".to_string(),
                recoverable: true,
            })
        );
        Ok(())
    }

    #[test]
    fn returns_unknown_seed_failure() -> Result<(), GraphExpandError> {
        let mut input = input();
        input.seed_chunk_ids = vec!["missing".to_string()];

        let output = expand_graph(&input, &graph())?;

        assert_eq!(
            output.failure,
            Some(GraphExpandFailure {
                code: "UNKNOWN_SEED_CHUNK".to_string(),
                message: "no graph evidence matched the seed chunk ids".to_string(),
                recoverable: true,
            })
        );
        Ok(())
    }

    #[test]
    fn rejects_invalid_input() {
        let mut missing_path = input();
        missing_path.graph_path = " ".to_string();
        assert_eq!(
            expand_graph(&missing_path, &graph()),
            Err(GraphExpandError::MissingGraphPath)
        );

        let mut missing_seed = input();
        missing_seed.seed_chunk_ids = vec![" ".to_string()];
        assert_eq!(
            expand_graph(&missing_seed, &graph()),
            Err(GraphExpandError::MissingSeedChunkIds)
        );

        let mut missing_trace = input();
        missing_trace.trace_id = " ".to_string();
        assert_eq!(
            expand_graph(&missing_trace, &graph()),
            Err(GraphExpandError::MissingTraceId)
        );
    }

    #[test]
    fn rejects_invalid_bounds() {
        let mut invalid_hops = input();
        invalid_hops.max_hops = Some(4);
        assert_eq!(
            expand_graph(&invalid_hops, &graph()),
            Err(GraphExpandError::InvalidMaxHops)
        );

        let mut invalid_zero_edges = input();
        invalid_zero_edges.max_edges = Some(0);
        assert_eq!(
            expand_graph(&invalid_zero_edges, &graph()),
            Err(GraphExpandError::InvalidMaxEdges)
        );

        let mut invalid_many_edges = input();
        invalid_many_edges.max_edges = Some(101);
        assert_eq!(
            expand_graph(&invalid_many_edges, &graph()),
            Err(GraphExpandError::InvalidMaxEdges)
        );
    }

    #[test]
    fn formats_error_messages() {
        assert_eq!(
            GraphExpandError::MissingGraphPath.to_string(),
            "missing graph path"
        );
        assert_eq!(
            GraphExpandError::MissingSeedChunkIds.to_string(),
            "missing seed chunk ids"
        );
        assert_eq!(
            GraphExpandError::MissingTraceId.to_string(),
            "missing trace id"
        );
        assert_eq!(
            GraphExpandError::InvalidMaxHops.to_string(),
            "max hops must be between 0 and 3"
        );
        assert_eq!(
            GraphExpandError::InvalidMaxEdges.to_string(),
            "max edges must be between 1 and 100"
        );
    }

    fn ids(nodes: &[GraphNode]) -> Vec<&str> {
        nodes.iter().map(|node| node.node_id.as_str()).collect()
    }

    fn edge_ids(edges: &[GraphEdge]) -> Vec<&str> {
        edges.iter().map(|edge| edge.edge_id.as_str()).collect()
    }
}
