#![forbid(unsafe_code)]
#![warn(clippy::all, clippy::pedantic)]

const DEFAULT_MAX_SOURCES: usize = 5;
const MAX_SOURCES: usize = 20;

const WORKFLOW_STEPS: [WorkflowStep; 6] = [
    WorkflowStep {
        node_id: "retrieve_sources",
        capability_id: "knowledge.retrieve",
    },
    WorkflowStep {
        node_id: "expand_graph_context",
        capability_id: "knowledge.graph.expand",
    },
    WorkflowStep {
        node_id: "pack_context",
        capability_id: "knowledge.context.pack",
    },
    WorkflowStep {
        node_id: "run_inference",
        capability_id: "knowledge.infer",
    },
    WorkflowStep {
        node_id: "validate_grounding",
        capability_id: "knowledge.answer.validate",
    },
    WorkflowStep {
        node_id: "format_answer",
        capability_id: "knowledge.answer.format",
    },
];

/// Returns the stable identifier for the query answer crate.
#[must_use]
pub const fn crate_name() -> &'static str {
    "youaskm3-knowledge-query-answer"
}

/// One Traverse workflow step required by `knowledge.query.answer`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WorkflowStep {
    /// Stable workflow node id.
    pub node_id: &'static str,
    /// Capability executed at this node.
    pub capability_id: &'static str,
}

/// Contract-shaped query answer input.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct QueryAnswerInput {
    /// User question.
    pub query: String,
    /// Optional conversation id.
    pub conversation_id: Option<String>,
    /// Optional artifact ids or paths to constrain retrieval.
    pub artifact_scope: Vec<String>,
    /// Optional source limit.
    pub max_sources: Option<usize>,
    /// Trace id generated by the Traverse workflow.
    pub trace_id: String,
}

/// Validated workflow plan for the Traverse runtime.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct QueryAnswerPlan {
    /// Normalized user question.
    pub query: String,
    /// Optional normalized conversation id.
    pub conversation_id: Option<String>,
    /// Normalized artifact scope.
    pub artifact_scope: Vec<String>,
    /// Applied source limit.
    pub max_sources: usize,
    /// Ordered Traverse workflow steps.
    pub steps: Vec<WorkflowStep>,
    /// Trace id copied from the Traverse workflow.
    pub trace_id: String,
}

/// Errors returned when the workflow entrypoint input is invalid.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum QueryAnswerError {
    /// Query was empty after trimming.
    MissingQuery,
    /// Trace id was empty after trimming.
    MissingTraceId,
    /// Requested source limit is outside the MVP contract range.
    InvalidMaxSources,
}

impl std::fmt::Display for QueryAnswerError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingQuery => f.write_str("missing answer query"),
            Self::MissingTraceId => f.write_str("missing trace id"),
            Self::InvalidMaxSources => f.write_str("max sources must be between 1 and 20"),
        }
    }
}

impl std::error::Error for QueryAnswerError {}

/// Validates the user-facing workflow entrypoint without executing child capabilities.
///
/// Traverse owns workflow composition and child capability execution. This crate
/// provides a real WASM entrypoint artifact for the `knowledge.query.answer`
/// contract while keeping retrieval, graph expansion, context packing,
/// inference, validation, and formatting in their separate governed components.
///
/// # Errors
///
/// Returns an error when required workflow input is missing or out of range.
pub fn plan_query_answer(input: &QueryAnswerInput) -> Result<QueryAnswerPlan, QueryAnswerError> {
    let query = normalize_text(&input.query);
    if query.is_empty() {
        return Err(QueryAnswerError::MissingQuery);
    }

    let trace_id = input.trace_id.trim();
    if trace_id.is_empty() {
        return Err(QueryAnswerError::MissingTraceId);
    }

    let max_sources = normalize_max_sources(input.max_sources)?;
    let artifact_scope = input
        .artifact_scope
        .iter()
        .map(|item| normalize_text(item))
        .filter(|item| !item.is_empty())
        .collect::<Vec<_>>();

    Ok(QueryAnswerPlan {
        query,
        conversation_id: input
            .conversation_id
            .as_deref()
            .map(normalize_text)
            .filter(|value| !value.is_empty()),
        artifact_scope,
        max_sources,
        steps: WORKFLOW_STEPS.to_vec(),
        trace_id: trace_id.to_string(),
    })
}

/// Returns the ordered child capabilities required by `knowledge.query.answer`.
#[must_use]
pub fn workflow_steps() -> &'static [WorkflowStep] {
    &WORKFLOW_STEPS
}

fn normalize_max_sources(value: Option<usize>) -> Result<usize, QueryAnswerError> {
    match value {
        Some(0) => Err(QueryAnswerError::InvalidMaxSources),
        Some(value) if value > MAX_SOURCES => Err(QueryAnswerError::InvalidMaxSources),
        Some(value) => Ok(value),
        None => Ok(DEFAULT_MAX_SOURCES),
    }
}

fn normalize_text(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[cfg(test)]
mod tests {
    use super::{
        QueryAnswerError, QueryAnswerInput, crate_name, plan_query_answer, workflow_steps,
    };

    fn input() -> QueryAnswerInput {
        QueryAnswerInput {
            query: "  What is portable knowledge?  ".to_string(),
            conversation_id: Some("  convo-1 ".to_string()),
            artifact_scope: vec![" artifact-a ".to_string(), " ".to_string()],
            max_sources: None,
            trace_id: "trace-1".to_string(),
        }
    }

    #[test]
    fn crate_name_is_stable() {
        assert_eq!(crate_name(), "youaskm3-knowledge-query-answer");
    }

    #[test]
    fn plans_ordered_child_capabilities() -> Result<(), String> {
        let plan = plan_query_answer(&input()).map_err(|error| error.to_string())?;

        assert_eq!(plan.query, "What is portable knowledge?");
        assert_eq!(plan.conversation_id.as_deref(), Some("convo-1"));
        assert_eq!(plan.artifact_scope, ["artifact-a"]);
        assert_eq!(plan.max_sources, 5);
        assert_eq!(plan.trace_id, "trace-1");
        assert_eq!(plan.steps, workflow_steps());
        assert_eq!(plan.steps[0].capability_id, "knowledge.retrieve");
        assert_eq!(plan.steps[5].capability_id, "knowledge.answer.format");
        Ok(())
    }

    #[test]
    fn applies_explicit_source_limit() -> Result<(), String> {
        let mut input = input();
        input.max_sources = Some(20);

        let plan = plan_query_answer(&input).map_err(|error| error.to_string())?;

        assert_eq!(plan.max_sources, 20);
        Ok(())
    }

    #[test]
    fn rejects_missing_required_fields() -> Result<(), String> {
        let mut missing_query = input();
        missing_query.query.clear();
        assert_eq!(
            query_answer_error(plan_query_answer(&missing_query))?,
            QueryAnswerError::MissingQuery
        );

        let mut missing_trace = input();
        missing_trace.trace_id.clear();
        assert_eq!(
            query_answer_error(plan_query_answer(&missing_trace))?,
            QueryAnswerError::MissingTraceId
        );
        Ok(())
    }

    #[test]
    fn rejects_invalid_source_limit() -> Result<(), String> {
        let mut input = input();
        input.max_sources = Some(0);
        assert_eq!(
            query_answer_error(plan_query_answer(&input))?,
            QueryAnswerError::InvalidMaxSources
        );

        input.max_sources = Some(21);
        assert_eq!(
            query_answer_error(plan_query_answer(&input))?,
            QueryAnswerError::InvalidMaxSources
        );
        Ok(())
    }

    fn query_answer_error(
        result: Result<super::QueryAnswerPlan, QueryAnswerError>,
    ) -> Result<QueryAnswerError, String> {
        match result {
            Ok(plan) => Err(format!("expected query answer error, got {plan:?}")),
            Err(error) => Ok(error),
        }
    }
}
