#!/usr/bin/env ruby
# frozen_string_literal: true

require "digest"
require "json"
require "pathname"

ROOT = Pathname.new(__dir__).join("..").expand_path
SKILL_DIR = ROOT.join("docs", "reasoning-assistant-skill")
MANIFEST_PATH = SKILL_DIR.join("manifest.json")
LOCAL_PATH_PATTERNS = [
  %r{/Users/},
  %r{/home/},
  %r{[A-Za-z]:\\}
].freeze

def read_manifest
  JSON.parse(MANIFEST_PATH.read)
rescue JSON::ParserError => error
  abort "Invalid JSON in #{MANIFEST_PATH.relative_path_from(ROOT)}: #{error.message}"
end

def render_adapter(manifest, adapter, canonical)
  digest = Digest::SHA256.hexdigest(canonical)
  <<~MARKDOWN
    <!-- Generated by scripts/generate-reasoning-skill-adapters.rb. Do not edit by hand. -->
    <!-- Canonical source: docs/reasoning-assistant-skill/#{manifest.fetch("canonical_source")} -->
    <!-- Canonical SHA256: #{digest} -->

    # #{manifest.fetch("title")} - #{adapter.fetch("label")} Adapter

    #{adapter.fetch("platform_note")}

    ## Adapter Contract

    - Source skill id: `#{manifest.fetch("skill_id")}`
    - Source version: `#{manifest.fetch("version")}`
    - Handoff command: `#{manifest.fetch("handoff_command")}`
    - Required package files: #{manifest.fetch("required_package_files").map { |file| "`#{file}`" }.join(", ")}
    - Package modes: #{manifest.fetch("package_modes").map { |mode| "`#{mode}`" }.join(", ")}

    ## Canonical Instructions

    #{canonical}
  MARKDOWN
end

def validate_rendered!(manifest, path, content)
  manifest.fetch("required_protocol_terms").each do |term|
    abort "#{path.relative_path_from(ROOT)} is missing required protocol term: #{term}" unless content.include?(term)
  end

  LOCAL_PATH_PATTERNS.each do |pattern|
    abort "#{path.relative_path_from(ROOT)} contains a hardcoded local path pattern: #{pattern.inspect}" if content.match?(pattern)
  end
end

manifest = read_manifest
canonical_path = SKILL_DIR.join(manifest.fetch("canonical_source"))
canonical = canonical_path.read
check_only = ARGV.include?("--check")

manifest.fetch("adapters").each do |adapter|
  output_path = SKILL_DIR.join(adapter.fetch("output"))
  rendered = render_adapter(manifest, adapter, canonical)
  validate_rendered!(manifest, output_path, rendered)

  if check_only
    unless output_path.file?
      abort "Missing generated adapter: #{output_path.relative_path_from(ROOT)}"
    end

    existing = output_path.read
    unless existing == rendered
      abort "Generated adapter is stale: #{output_path.relative_path_from(ROOT)}"
    end
  else
    output_path.dirname.mkpath
    output_path.write(rendered)
  end
end

puts check_only ? "Reasoning skill adapter drift check passed." : "Reasoning skill adapters generated."
