#!/usr/bin/env ruby
# frozen_string_literal: true

require "digest"
require "json"
require "pathname"

ROOT = Pathname.new(__dir__).join("..").expand_path
SKILL_DIR = ROOT.join("docs", "reasoning-assistant-skill")
MANIFEST_PATH = SKILL_DIR.join("manifest.json")
DISTRIBUTION_PATH = SKILL_DIR.join("distribution.json")
LOCAL_PATH_PATTERNS = [
  %r{/Users/},
  %r{/home/},
  %r{[A-Za-z]:\\}
].freeze

def read_json(path)
  JSON.parse(path.read)
rescue JSON::ParserError => error
  abort "Invalid JSON in #{path.relative_path_from(ROOT)}: #{error.message}"
end

def adapter_by_id(manifest, adapter_id)
  manifest.fetch("adapters").find { |adapter| adapter.fetch("id") == adapter_id } ||
    abort("Unknown adapter id in distribution metadata: #{adapter_id}")
end

def package_manifest(manifest, distribution, package, adapter, adapter_body)
  {
    "schema_version" => distribution.fetch("package_schema_version"),
    "package_id" => "#{manifest.fetch("skill_id")}.#{package.fetch("id")}",
    "package_version" => package.fetch("package_version"),
    "platform" => {
      "id" => package.fetch("id"),
      "label" => package.fetch("label")
    },
    "source_skill" => {
      "id" => manifest.fetch("skill_id"),
      "version" => manifest.fetch("version"),
      "canonical_source" => "docs/reasoning-assistant-skill/#{manifest.fetch("canonical_source")}"
    },
    "source_adapter" => {
      "id" => adapter.fetch("id"),
      "path" => "docs/reasoning-assistant-skill/#{adapter.fetch("output")}",
      "sha256" => Digest::SHA256.hexdigest(adapter_body)
    },
    "required_files" => [
      "manifest.json",
      "instructions.md",
      "README.md"
    ],
    "handoff_command" => manifest.fetch("handoff_command"),
    "limitations" => {
      "export_shape" => package.fetch("export_shape"),
      "action_tool_availability" => package.fetch("action_tool_availability"),
      "local_file_handoff" => package.fetch("local_file_handoff"),
      "marketplace_publication" => package.fetch("marketplace_publication")
    }
  }
end

def render_readme(manifest, distribution, package, adapter)
  <<~MARKDOWN
    <!-- Generated by scripts/generate-assistant-distribution-packages.rb. Do not edit by hand. -->

    # #{manifest.fetch("title")} - #{package.fetch("label")} Package

    This package distributes the generated #{adapter.fetch("label")} adapter without changing the canonical reasoning skill behavior.

    ## Package Contract

    - Package schema version: `#{distribution.fetch("package_schema_version")}`
    - Package version: `#{package.fetch("package_version")}`
    - Source skill id: `#{manifest.fetch("skill_id")}`
    - Source skill version: `#{manifest.fetch("version")}`
    - Source adapter: `docs/reasoning-assistant-skill/#{adapter.fetch("output")}`
    - Handoff command: `#{manifest.fetch("handoff_command")}`

    ## Files

    - `manifest.json`: package metadata and source adapter hash.
    - `instructions.md`: generated platform adapter instructions.
    - `README.md`: package contract and platform limitations.

    ## Platform Limitations

    - Export shape: #{package.fetch("export_shape")}
    - Action/tool availability: #{package.fetch("action_tool_availability")}
    - Local file handoff: #{package.fetch("local_file_handoff")}
    - Marketplace publication: #{package.fetch("marketplace_publication")}
  MARKDOWN
end

def render_instructions(adapter_body)
  <<~MARKDOWN
    <!-- Generated by scripts/generate-assistant-distribution-packages.rb from the generated adapter. Do not edit by hand. -->

    #{adapter_body}
  MARKDOWN
end

def validate_no_local_paths!(path, content)
  LOCAL_PATH_PATTERNS.each do |pattern|
    abort "#{path.relative_path_from(ROOT)} contains a hardcoded local path pattern: #{pattern.inspect}" if content.match?(pattern)
  end
end

def validate_instructions!(path, content, manifest)
  manifest.fetch("required_protocol_terms").each do |term|
    abort "#{path.relative_path_from(ROOT)} is missing required protocol term: #{term}" unless content.include?(term)
  end

  validate_no_local_paths!(path, content)
end

def write_or_check(path, content, check_only)
  if check_only
    abort "Missing generated package artifact: #{path.relative_path_from(ROOT)}" unless path.file?
    abort "Generated package artifact is stale: #{path.relative_path_from(ROOT)}" unless path.read == content
  else
    path.dirname.mkpath
    path.write(content)
  end
end

def check_manifest_versions!(path, manifest, distribution)
  return unless path.file?

  existing = read_json(path)
  existing_skill_version = existing.fetch("source_skill").fetch("version")
  expected_skill_version = manifest.fetch("version")
  if existing_skill_version != expected_skill_version
    abort "#{path.relative_path_from(ROOT)} canonical version mismatch: expected #{expected_skill_version}, found #{existing_skill_version}"
  end

  existing_schema_version = existing.fetch("schema_version")
  expected_schema_version = distribution.fetch("package_schema_version")
  if existing_schema_version != expected_schema_version
    abort "#{path.relative_path_from(ROOT)} package schema version mismatch: expected #{expected_schema_version}, found #{existing_schema_version}"
  end
end

manifest = read_json(MANIFEST_PATH)
distribution = read_json(DISTRIBUTION_PATH)
check_only = ARGV.include?("--check")

distribution.fetch("packages").each do |package|
  adapter = adapter_by_id(manifest, package.fetch("adapter_id"))
  adapter_path = SKILL_DIR.join(adapter.fetch("output"))
  abort "Missing generated adapter for package #{package.fetch("id")}: #{adapter_path.relative_path_from(ROOT)}" unless adapter_path.file?

  adapter_body = adapter_path.read
  output_dir = SKILL_DIR.join(package.fetch("output_dir"))
  package_json = JSON.pretty_generate(package_manifest(manifest, distribution, package, adapter, adapter_body)) + "\n"
  instructions = render_instructions(adapter_body)
  readme = render_readme(manifest, distribution, package, adapter)

  validate_instructions!(output_dir.join("instructions.md"), instructions, manifest)
  validate_no_local_paths!(output_dir.join("README.md"), readme)
  validate_no_local_paths!(output_dir.join("manifest.json"), package_json)

  package_manifest_path = output_dir.join("manifest.json")
  check_manifest_versions!(package_manifest_path, manifest, distribution) if check_only

  write_or_check(package_manifest_path, package_json, check_only)
  write_or_check(output_dir.join("instructions.md"), instructions, check_only)
  write_or_check(output_dir.join("README.md"), readme, check_only)
end

puts check_only ? "Assistant distribution package drift check passed." : "Assistant distribution packages generated."
