#!/usr/bin/env ruby
# frozen_string_literal: true

require "digest"
require "json"
require "pathname"

ROOT = Pathname.new(__dir__).join("..").expand_path
SKILL_DIR = ROOT.join("docs", "reasoning-assistant-skill")
MANIFEST_PATH = SKILL_DIR.join("manifest.json")
LOCAL_PATH_PATTERNS = [
  %r{/Users/},
  %r{/home/},
  %r{[A-Za-z]:\\}
].freeze

def read_manifest
  JSON.parse(MANIFEST_PATH.read)
rescue JSON::ParserError => error
  abort "Invalid JSON in #{MANIFEST_PATH.relative_path_from(ROOT)}: #{error.message}"
end

def usage
  abort "Usage: ruby scripts/generate-reasoning-skill-adapters.rb [--check] [--persona-registry PATH --persona-id ID --output-dir PATH]"
end

def parse_options(argv)
  options = { "check" => false }
  until argv.empty?
    flag = argv.shift
    case flag
    when "--check"
      options["check"] = true
    when "--persona-registry"
      options["persona_registry"] = Pathname.new(argv.shift || usage)
    when "--persona-id"
      options["persona_id"] = argv.shift || usage
    when "--output-dir"
      options["output_dir"] = Pathname.new(argv.shift || usage)
    else
      usage
    end
  end
  options
end

def persona_context(options)
  return nil unless options["persona_registry"] || options["persona_id"] || options["output_dir"]
  usage unless options["persona_registry"] && options["persona_id"] && options["output_dir"]

  registry = JSON.parse(options.fetch("persona_registry").read)
  persona = registry.fetch("personas").find { |item| item.fetch("persona_id") == options.fetch("persona_id") } ||
    abort("Unknown persona id: #{options.fetch("persona_id")}")
  allowed_shared_scopes = registry.fetch("shared_scopes").select do |scope|
    scope.fetch("allowed_persona_ids").include?(persona.fetch("persona_id"))
  end.map { |scope| scope.fetch("scope_id") }
  {
    "persona_id" => persona.fetch("persona_id"),
    "label" => persona.fetch("label"),
    "role" => persona.fetch("assistant_metadata").fetch("role"),
    "allowed_shared_scopes" => allowed_shared_scopes
  }
end

def persona_section(context)
  return "" unless context

  scopes = context.fetch("allowed_shared_scopes")
  <<~MARKDOWN
    ## Persona Context

    - Persona id: `#{context.fetch("persona_id")}`
    - Persona label: `#{context.fetch("label")}`
    - Persona role: `#{context.fetch("role")}`
    - Allowed shared scopes: #{scopes.empty? ? "`none`" : scopes.map { |scope| "`#{scope}`" }.join(", ")}

    Do not embed private persona knowledge in this adapter. Retrieve persona-specific and shared-scope knowledge from the configured knowledge store at runtime.

  MARKDOWN
end

def render_adapter(manifest, adapter, canonical, persona)
  digest = Digest::SHA256.hexdigest(canonical)
  rendered = <<~MARKDOWN
    <!-- Generated by scripts/generate-reasoning-skill-adapters.rb. Do not edit by hand. -->
    <!-- Canonical source: docs/reasoning-assistant-skill/#{manifest.fetch("canonical_source")} -->
    <!-- Canonical SHA256: #{digest} -->

    # #{manifest.fetch("title")} - #{adapter.fetch("label")} Adapter

    #{adapter.fetch("platform_note")}

    ## Adapter Contract

    - Source skill id: `#{manifest.fetch("skill_id")}`
    - Source version: `#{manifest.fetch("version")}`
    - Handoff command: `#{manifest.fetch("handoff_command")}`
    - Required package files: #{manifest.fetch("required_package_files").map { |file| "`#{file}`" }.join(", ")}
    - Package modes: #{manifest.fetch("package_modes").map { |mode| "`#{mode}`" }.join(", ")}

    ## Canonical Instructions

    #{canonical}
  MARKDOWN
  return rendered unless persona

  rendered.sub("\n## Canonical Instructions", "\n#{persona_section(persona)}\n## Canonical Instructions")
end

def validate_rendered!(manifest, path, content)
  manifest.fetch("required_protocol_terms").each do |term|
    abort "#{path.relative_path_from(ROOT)} is missing required protocol term: #{term}" unless content.include?(term)
  end

  LOCAL_PATH_PATTERNS.each do |pattern|
    abort "#{path.relative_path_from(ROOT)} contains a hardcoded local path pattern: #{pattern.inspect}" if content.match?(pattern)
  end
end

manifest = read_manifest
canonical_path = SKILL_DIR.join(manifest.fetch("canonical_source"))
canonical = canonical_path.read
options = parse_options(ARGV)
check_only = options.fetch("check")
persona = persona_context(options)
output_root = options["output_dir"] ? options.fetch("output_dir").expand_path : SKILL_DIR

manifest.fetch("adapters").each do |adapter|
  output_path = output_root.join(adapter.fetch("output"))
  rendered = render_adapter(manifest, adapter, canonical, persona)
  validate_rendered!(manifest, output_path, rendered)

  if check_only
    unless output_path.file?
      abort "Missing generated adapter: #{output_path.relative_path_from(ROOT)}"
    end

    existing = output_path.read
    unless existing == rendered
      abort "Generated adapter is stale: #{output_path.relative_path_from(ROOT)}"
    end
  else
    output_path.dirname.mkpath
    output_path.write(rendered)
  end
end

puts check_only ? "Reasoning skill adapter drift check passed." : "Reasoning skill adapters generated."
