#![forbid(unsafe_code)]
#![warn(clippy::all, clippy::pedantic)]

const MIN_TOKEN_BUDGET: usize = 256;
const MIN_TRUNCATED_BLOCK_TOKENS: usize = 24;

/// Returns the stable identifier for the context pack crate.
#[must_use]
pub const fn crate_name() -> &'static str {
    "youaskm3-knowledge-context-pack"
}

/// Retrieved source chunk supplied to the context packer.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RetrievedChunk {
    /// Stable chunk id.
    pub chunk_id: String,
    /// Citation id used by downstream answer formatting.
    pub citation_id: String,
    /// Source path preserved for grounding.
    pub source_path: String,
    /// Retrieved text snippet.
    pub text: String,
}

/// Graph evidence supplied to the context packer.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GraphEvidence {
    /// Stable graph edge id.
    pub edge_id: String,
    /// Graph node ids participating in the evidence.
    pub node_ids: Vec<String>,
    /// Source chunk ids supporting this graph evidence.
    pub supporting_chunk_ids: Vec<String>,
    /// Human-readable graph summary.
    pub summary: String,
}

/// Contract-shaped context pack input.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContextPackInput {
    /// User question.
    pub query: String,
    /// Retrieved source chunks in ranking order.
    pub retrieved_chunks: Vec<RetrievedChunk>,
    /// Graph evidence in deterministic workflow order.
    pub graph_evidence: Vec<GraphEvidence>,
    /// Maximum token budget for the context string.
    pub token_budget: usize,
    /// Trace id generated by the Traverse workflow.
    pub trace_id: String,
}

/// Contract-shaped context pack output.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContextPackOutput {
    /// Packed context for inference.
    pub context: String,
    /// Included source chunk ids.
    pub included_chunk_ids: Vec<String>,
    /// Included graph edge ids.
    pub included_edge_ids: Vec<String>,
    /// Stable omission or truncation reasons.
    pub omitted_reasons: Vec<String>,
    /// Trace id copied from the Traverse workflow.
    pub trace_id: String,
}

/// Errors returned by context packing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ContextPackError {
    /// Query was empty after trimming.
    MissingQuery,
    /// No source or graph evidence was provided.
    MissingEvidence,
    /// Trace id was empty after trimming.
    MissingTraceId,
    /// Token budget is smaller than the MVP contract minimum.
    BudgetTooSmall,
}

impl std::fmt::Display for ContextPackError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingQuery => f.write_str("missing context query"),
            Self::MissingEvidence => f.write_str("missing context evidence"),
            Self::MissingTraceId => f.write_str("missing trace id"),
            Self::BudgetTooSmall => f.write_str("context token budget is below 256"),
        }
    }
}

impl std::error::Error for ContextPackError {}

/// Packs deterministic source and graph context without filesystem, network, or environment access.
///
/// # Errors
///
/// Returns an error when required input is missing or the budget is below the
/// first-MVP contract minimum.
pub fn pack_context(input: &ContextPackInput) -> Result<ContextPackOutput, ContextPackError> {
    let query = normalize_text(&input.query);
    if query.is_empty() {
        return Err(ContextPackError::MissingQuery);
    }

    let trace_id = input.trace_id.trim().to_string();
    if trace_id.is_empty() {
        return Err(ContextPackError::MissingTraceId);
    }

    if input.token_budget < MIN_TOKEN_BUDGET {
        return Err(ContextPackError::BudgetTooSmall);
    }

    if input.retrieved_chunks.is_empty() && input.graph_evidence.is_empty() {
        return Err(ContextPackError::MissingEvidence);
    }

    let mut sections = vec![format!("Question:\n{query}")];
    let mut used_tokens = token_count(&sections[0]);
    let mut included_chunk_ids = Vec::new();
    let mut included_edge_ids = Vec::new();
    let mut omitted_reasons = Vec::new();

    for chunk in &input.retrieved_chunks {
        let block = source_block(chunk);
        if append_block(
            &mut sections,
            &mut used_tokens,
            input.token_budget,
            &block,
            BlockOmission::Chunk(chunk.chunk_id.as_str()),
            &mut omitted_reasons,
        ) {
            included_chunk_ids.push(chunk.chunk_id.clone());
        }
    }

    for graph in &input.graph_evidence {
        let block = graph_block(graph);
        if append_block(
            &mut sections,
            &mut used_tokens,
            input.token_budget,
            &block,
            BlockOmission::Graph(graph.edge_id.as_str()),
            &mut omitted_reasons,
        ) {
            included_edge_ids.push(graph.edge_id.clone());
        }
    }

    Ok(ContextPackOutput {
        context: sections.join("\n\n"),
        included_chunk_ids,
        included_edge_ids,
        omitted_reasons,
        trace_id,
    })
}

#[derive(Clone, Copy)]
enum BlockOmission<'a> {
    Chunk(&'a str),
    Graph(&'a str),
}

fn append_block(
    sections: &mut Vec<String>,
    used_tokens: &mut usize,
    budget: usize,
    block: &str,
    omission: BlockOmission<'_>,
    omitted_reasons: &mut Vec<String>,
) -> bool {
    let block_tokens = token_count(block);
    let remaining = budget.saturating_sub(*used_tokens);

    if block_tokens <= remaining {
        sections.push(block.to_string());
        *used_tokens += block_tokens;
        return true;
    }

    if remaining >= MIN_TRUNCATED_BLOCK_TOKENS {
        let truncated = truncate_to_tokens(block, remaining);
        sections.push(truncated);
        *used_tokens = budget;
        omitted_reasons.push(truncated_reason(omission));
        return true;
    }

    omitted_reasons.push(omitted_reason(omission));
    false
}

fn source_block(chunk: &RetrievedChunk) -> String {
    format!(
        "Source {citation_id}\nchunk_id: {chunk_id}\nsource_path: {source_path}\nexcerpt: {text}",
        citation_id = normalize_text(&chunk.citation_id),
        chunk_id = normalize_text(&chunk.chunk_id),
        source_path = normalize_text(&chunk.source_path),
        text = normalize_text(&chunk.text),
    )
}

fn graph_block(graph: &GraphEvidence) -> String {
    format!(
        "Graph edge {edge_id}\nnodes: {nodes}\nsupporting_chunks: {chunks}\nsummary: {summary}",
        edge_id = normalize_text(&graph.edge_id),
        nodes = graph.node_ids.join(", "),
        chunks = graph.supporting_chunk_ids.join(", "),
        summary = normalize_text(&graph.summary),
    )
}

fn omitted_reason(omission: BlockOmission<'_>) -> String {
    match omission {
        BlockOmission::Chunk(id) => format!("omitted chunk {id}: token budget exhausted"),
        BlockOmission::Graph(id) => format!("omitted graph edge {id}: token budget exhausted"),
    }
}

fn truncated_reason(omission: BlockOmission<'_>) -> String {
    match omission {
        BlockOmission::Chunk(id) => format!("truncated chunk {id}: token budget exhausted"),
        BlockOmission::Graph(id) => format!("truncated graph edge {id}: token budget exhausted"),
    }
}

fn truncate_to_tokens(value: &str, limit: usize) -> String {
    value
        .split_whitespace()
        .take(limit)
        .collect::<Vec<_>>()
        .join(" ")
}

fn token_count(value: &str) -> usize {
    value.split_whitespace().count()
}

fn normalize_text(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[cfg(test)]
mod tests {
    use super::{
        ContextPackError, ContextPackInput, GraphEvidence, RetrievedChunk, crate_name, pack_context,
    };

    fn chunk(id: &str, text: &str) -> RetrievedChunk {
        RetrievedChunk {
            chunk_id: id.to_string(),
            citation_id: format!("cite-{id}"),
            source_path: format!("knowledge/{id}.md"),
            text: text.to_string(),
        }
    }

    fn graph(id: &str) -> GraphEvidence {
        GraphEvidence {
            edge_id: id.to_string(),
            node_ids: vec!["node-a".to_string(), "node-b".to_string()],
            supporting_chunk_ids: vec!["chunk-a".to_string()],
            summary: "  graph   evidence summary ".to_string(),
        }
    }

    fn input() -> ContextPackInput {
        ContextPackInput {
            query: "  What is portable knowledge? ".to_string(),
            retrieved_chunks: vec![chunk("chunk-a", "Portable knowledge stays in files.")],
            graph_evidence: vec![graph("edge-a")],
            token_budget: 256,
            trace_id: "trace-ctx".to_string(),
        }
    }

    #[test]
    fn crate_name_matches_package() {
        assert_eq!(crate_name(), "youaskm3-knowledge-context-pack");
    }

    #[test]
    fn packs_source_and_graph_context() -> Result<(), ContextPackError> {
        let output = pack_context(&input())?;

        assert!(
            output
                .context
                .contains("Question:\nWhat is portable knowledge?")
        );
        assert!(output.context.contains("Source cite-chunk-a"));
        assert!(output.context.contains("Graph edge edge-a"));
        assert_eq!(output.included_chunk_ids, ["chunk-a"]);
        assert_eq!(output.included_edge_ids, ["edge-a"]);
        assert_eq!(output.trace_id, "trace-ctx");
        Ok(())
    }

    #[test]
    fn preserves_citation_and_source_mapping() -> Result<(), ContextPackError> {
        let output = pack_context(&input())?;

        assert!(output.context.contains("chunk_id: chunk-a"));
        assert!(output.context.contains("source_path: knowledge/chunk-a.md"));
        assert!(output.context.contains("supporting_chunks: chunk-a"));
        Ok(())
    }

    #[test]
    fn output_is_deterministic() -> Result<(), ContextPackError> {
        let first = pack_context(&input())?;
        let second = pack_context(&input())?;

        assert_eq!(first, second);
        Ok(())
    }

    #[test]
    fn truncates_large_blocks_to_budget() -> Result<(), ContextPackError> {
        let mut input = input();
        input.retrieved_chunks = vec![chunk("large", &"token ".repeat(400))];
        input.graph_evidence.clear();
        input.token_budget = 256;

        let output = pack_context(&input)?;

        assert_eq!(output.included_chunk_ids, ["large"]);
        assert_eq!(
            output.omitted_reasons,
            ["truncated chunk large: token budget exhausted"]
        );
        assert!(output.context.split_whitespace().count() <= 256);
        Ok(())
    }

    #[test]
    fn omits_blocks_when_budget_is_exhausted() -> Result<(), ContextPackError> {
        let mut input = input();
        input.retrieved_chunks = vec![
            chunk("large", &"token ".repeat(260)),
            chunk("omitted", "short text"),
        ];
        input.graph_evidence.clear();
        input.token_budget = 256;

        let output = pack_context(&input)?;

        assert_eq!(output.included_chunk_ids, ["large"]);
        assert_eq!(
            output.omitted_reasons,
            [
                "truncated chunk large: token budget exhausted",
                "omitted chunk omitted: token budget exhausted",
            ]
        );
        Ok(())
    }

    #[test]
    fn truncates_and_omits_graph_blocks() -> Result<(), ContextPackError> {
        let mut input = input();
        input.retrieved_chunks.clear();
        input.graph_evidence = vec![
            GraphEvidence {
                edge_id: "large-edge".to_string(),
                node_ids: vec!["node-a".to_string(), "node-b".to_string()],
                supporting_chunk_ids: vec!["chunk-a".to_string()],
                summary: "graph-token ".repeat(260),
            },
            graph("omitted-edge"),
        ];
        input.token_budget = 256;

        let output = pack_context(&input)?;

        assert_eq!(output.included_edge_ids, ["large-edge"]);
        assert_eq!(
            output.omitted_reasons,
            [
                "truncated graph edge large-edge: token budget exhausted",
                "omitted graph edge omitted-edge: token budget exhausted",
            ]
        );
        Ok(())
    }

    #[test]
    fn rejects_missing_query() {
        let mut input = input();
        input.query = " ".to_string();

        assert_eq!(pack_context(&input), Err(ContextPackError::MissingQuery));
    }

    #[test]
    fn rejects_missing_trace_id() {
        let mut input = input();
        input.trace_id = " ".to_string();

        assert_eq!(pack_context(&input), Err(ContextPackError::MissingTraceId));
    }

    #[test]
    fn rejects_too_small_budget() {
        let mut input = input();
        input.token_budget = 255;

        assert_eq!(pack_context(&input), Err(ContextPackError::BudgetTooSmall));
    }

    #[test]
    fn rejects_missing_evidence() {
        let mut input = input();
        input.retrieved_chunks.clear();
        input.graph_evidence.clear();

        assert_eq!(pack_context(&input), Err(ContextPackError::MissingEvidence));
    }

    #[test]
    fn formats_error_messages() {
        assert_eq!(
            ContextPackError::MissingQuery.to_string(),
            "missing context query"
        );
        assert_eq!(
            ContextPackError::MissingEvidence.to_string(),
            "missing context evidence"
        );
        assert_eq!(
            ContextPackError::MissingTraceId.to_string(),
            "missing trace id"
        );
        assert_eq!(
            ContextPackError::BudgetTooSmall.to_string(),
            "context token budget is below 256"
        );
    }
}
