#![forbid(unsafe_code)]
#![warn(clippy::all, clippy::pedantic)]

/// Returns the stable identifier for the answer format crate.
#[must_use]
pub const fn crate_name() -> &'static str {
    "youaskm3-knowledge-answer-format"
}

/// Output target for the formatted answer envelope.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FormatTarget {
    /// Browser chat surface.
    Chat,
    /// MCP/reporting surface.
    Mcp,
}

/// Validation status from upstream answer validation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ValidationStatus {
    /// Answer is grounded and can be displayed as complete.
    Valid,
    /// Answer has partial evidence or missing evidence.
    Partial,
    /// Answer failed validation.
    Invalid,
}

/// Stable failure payload carried through formatted answers.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FormatFailure {
    /// Stable machine-readable failure code.
    pub code: String,
    /// Human-readable failure message.
    pub message: String,
    /// Whether the caller may retry after changing input or setup.
    pub recoverable: bool,
}

/// Validation details supplied by upstream validation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FormatValidation {
    /// Upstream validation status.
    pub status: ValidationStatus,
    /// Stable validation check identifiers.
    pub checks: Vec<String>,
    /// Optional failure payload.
    pub failure: Option<FormatFailure>,
}

/// Source citation supplied to the formatter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FormatCitation {
    /// Stable artifact id.
    pub artifact_id: String,
    /// Stable chunk id.
    pub chunk_id: String,
    /// Source path to show in clients.
    pub source_path: String,
    /// Short excerpt used by source cards.
    pub excerpt: String,
}

/// Graph evidence supplied to the formatter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FormatGraphEvidence {
    /// Graph node ids used by the answer.
    pub node_ids: Vec<String>,
    /// Graph edge ids used by the answer.
    pub edge_ids: Vec<String>,
    /// Source chunk ids supporting the graph evidence.
    pub supporting_chunk_ids: Vec<String>,
}

/// Contract-shaped answer format input.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AnswerFormatInput {
    /// Raw answer text from inference or validation failure handling.
    pub raw_answer: String,
    /// Source citations to display.
    pub citations: Vec<FormatCitation>,
    /// Graph evidence to summarize.
    pub graph_evidence: Vec<FormatGraphEvidence>,
    /// Upstream validation payload.
    pub validation: FormatValidation,
    /// Target client surface.
    pub target: FormatTarget,
    /// Trace id generated by the Traverse workflow.
    pub trace_id: String,
}

/// Source card returned by the formatter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SourceCard {
    /// Stable display label.
    pub label: String,
    /// Stable artifact id.
    pub artifact_id: String,
    /// Stable chunk id.
    pub chunk_id: String,
    /// Source path to display.
    pub source_path: String,
    /// Normalized source excerpt.
    pub excerpt: String,
}

/// Graph card returned by the formatter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GraphCard {
    /// Stable display label.
    pub label: String,
    /// Node ids included in the evidence group.
    pub node_ids: Vec<String>,
    /// Edge ids included in the evidence group.
    pub edge_ids: Vec<String>,
    /// Supporting source chunk ids included in the evidence group.
    pub supporting_chunk_ids: Vec<String>,
    /// Summary suitable for chat and MCP clients.
    pub summary: String,
}

/// Display status returned by the formatter.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DisplayStatus {
    /// Grounded answer with source evidence.
    Grounded,
    /// Answer can be shown but should be reviewed.
    NeedsReview,
    /// Answer should be treated as failed.
    Failed,
}

/// Contract-shaped answer format output.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AnswerFormatOutput {
    /// Normalized answer text.
    pub answer: String,
    /// Source cards in stable citation order.
    pub source_cards: Vec<SourceCard>,
    /// Graph evidence cards.
    pub graph_cards: Vec<GraphCard>,
    /// Trace id copied from the Traverse workflow.
    pub trace_id: String,
    /// Client display status.
    pub display_status: DisplayStatus,
    /// Optional failure payload for failed validation.
    pub failure: Option<FormatFailure>,
}

/// Errors returned by answer formatting.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AnswerFormatError {
    /// Raw answer was empty after normalization.
    MissingAnswer,
    /// Trace id was empty after trimming.
    MissingTraceId,
}

impl std::fmt::Display for AnswerFormatError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingAnswer => f.write_str("missing answer text"),
            Self::MissingTraceId => f.write_str("missing trace id"),
        }
    }
}

impl std::error::Error for AnswerFormatError {}

/// Formats an answer envelope without filesystem, network, or environment access.
///
/// # Errors
///
/// Returns an error when the answer text or trace id is empty after trimming.
pub fn format_answer(input: AnswerFormatInput) -> Result<AnswerFormatOutput, AnswerFormatError> {
    let answer = normalize_text(&input.raw_answer);
    if answer.is_empty() {
        return Err(AnswerFormatError::MissingAnswer);
    }

    let trace_id = input.trace_id.trim().to_string();
    if trace_id.is_empty() {
        return Err(AnswerFormatError::MissingTraceId);
    }

    let source_cards = source_cards_for(input.target, &input.citations);
    let graph_cards = graph_cards_for(input.target, &input.graph_evidence);
    let display_status = display_status_for(input.validation.status, source_cards.is_empty());

    Ok(AnswerFormatOutput {
        answer,
        source_cards,
        graph_cards,
        trace_id,
        display_status,
        failure: input.validation.failure,
    })
}

fn source_cards_for(target: FormatTarget, citations: &[FormatCitation]) -> Vec<SourceCard> {
    citations
        .iter()
        .enumerate()
        .map(|(index, citation)| {
            let ordinal = index + 1;
            SourceCard {
                label: source_label_for(target, ordinal),
                artifact_id: citation.artifact_id.clone(),
                chunk_id: citation.chunk_id.clone(),
                source_path: citation.source_path.clone(),
                excerpt: normalize_text(&citation.excerpt),
            }
        })
        .collect()
}

fn graph_cards_for(target: FormatTarget, evidence: &[FormatGraphEvidence]) -> Vec<GraphCard> {
    evidence
        .iter()
        .enumerate()
        .map(|(index, graph)| {
            let ordinal = index + 1;
            GraphCard {
                label: graph_label_for(target, ordinal),
                node_ids: graph.node_ids.clone(),
                edge_ids: graph.edge_ids.clone(),
                supporting_chunk_ids: graph.supporting_chunk_ids.clone(),
                summary: graph_summary(graph),
            }
        })
        .collect()
}

fn display_status_for(status: ValidationStatus, has_no_citations: bool) -> DisplayStatus {
    match (status, has_no_citations) {
        (ValidationStatus::Invalid, _) => DisplayStatus::Failed,
        (ValidationStatus::Partial, _) | (ValidationStatus::Valid, true) => {
            DisplayStatus::NeedsReview
        }
        (ValidationStatus::Valid, false) => DisplayStatus::Grounded,
    }
}

fn source_label_for(target: FormatTarget, ordinal: usize) -> String {
    match target {
        FormatTarget::Chat => format!("[{ordinal}]"),
        FormatTarget::Mcp => format!("source:{ordinal}"),
    }
}

fn graph_label_for(target: FormatTarget, ordinal: usize) -> String {
    match target {
        FormatTarget::Chat => format!("Graph {ordinal}"),
        FormatTarget::Mcp => format!("graph:{ordinal}"),
    }
}

fn graph_summary(graph: &FormatGraphEvidence) -> String {
    format!(
        "{} node(s), {} edge(s), {} supporting chunk(s)",
        graph.node_ids.len(),
        graph.edge_ids.len(),
        graph.supporting_chunk_ids.len()
    )
}

fn normalize_text(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[cfg(test)]
mod tests {
    use super::{
        AnswerFormatError, AnswerFormatInput, DisplayStatus, FormatCitation, FormatFailure,
        FormatGraphEvidence, FormatTarget, FormatValidation, ValidationStatus, crate_name,
        format_answer,
    };

    fn citation(source_path: &str) -> FormatCitation {
        FormatCitation {
            artifact_id: "artifact-1".to_string(),
            chunk_id: "chunk-1".to_string(),
            source_path: source_path.to_string(),
            excerpt: "  Source-backed   excerpt. ".to_string(),
        }
    }

    fn graph_evidence() -> FormatGraphEvidence {
        FormatGraphEvidence {
            node_ids: vec!["node-1".to_string(), "node-2".to_string()],
            edge_ids: vec!["edge-1".to_string()],
            supporting_chunk_ids: vec!["chunk-1".to_string()],
        }
    }

    fn input(status: ValidationStatus) -> AnswerFormatInput {
        AnswerFormatInput {
            raw_answer: "  Portable\n\nanswer   text. ".to_string(),
            citations: vec![citation("knowledge/source.md")],
            graph_evidence: vec![graph_evidence()],
            validation: FormatValidation {
                status,
                checks: vec!["citations-present".to_string()],
                failure: None,
            },
            target: FormatTarget::Chat,
            trace_id: "trace-1".to_string(),
        }
    }

    #[test]
    fn crate_name_matches_package() {
        assert_eq!(crate_name(), "youaskm3-knowledge-answer-format");
    }

    #[test]
    fn formats_successful_grounded_answer() -> Result<(), AnswerFormatError> {
        let output = format_answer(input(ValidationStatus::Valid))?;

        assert_eq!(output.answer, "Portable answer text.");
        assert_eq!(output.trace_id, "trace-1");
        assert_eq!(output.display_status, DisplayStatus::Grounded);
        assert_eq!(output.source_cards[0].label, "[1]");
        assert_eq!(output.source_cards[0].excerpt, "Source-backed excerpt.");
        Ok(())
    }

    #[test]
    fn formats_partial_validation_as_needs_review() -> Result<(), AnswerFormatError> {
        let output = format_answer(input(ValidationStatus::Partial))?;

        assert_eq!(output.display_status, DisplayStatus::NeedsReview);
        Ok(())
    }

    #[test]
    fn formats_failed_validation_with_failure_payload() -> Result<(), AnswerFormatError> {
        let mut input = input(ValidationStatus::Invalid);
        input.validation.failure = Some(FormatFailure {
            code: "GROUNDING_FAILED".to_string(),
            message: "Answer did not satisfy citation validation.".to_string(),
            recoverable: true,
        });

        let output = format_answer(input)?;

        assert_eq!(output.display_status, DisplayStatus::Failed);
        assert_eq!(
            output.failure,
            Some(FormatFailure {
                code: "GROUNDING_FAILED".to_string(),
                message: "Answer did not satisfy citation validation.".to_string(),
                recoverable: true,
            })
        );
        Ok(())
    }

    #[test]
    fn marks_valid_answer_without_citations_as_needs_review() -> Result<(), AnswerFormatError> {
        let mut input = input(ValidationStatus::Valid);
        input.citations.clear();

        let output = format_answer(input)?;

        assert_eq!(output.source_cards, []);
        assert_eq!(output.display_status, DisplayStatus::NeedsReview);
        Ok(())
    }

    #[test]
    fn formats_graph_evidence_summary() -> Result<(), AnswerFormatError> {
        let output = format_answer(input(ValidationStatus::Valid))?;

        assert_eq!(output.graph_cards[0].label, "Graph 1");
        assert_eq!(
            output.graph_cards[0].summary,
            "2 node(s), 1 edge(s), 1 supporting chunk(s)"
        );
        Ok(())
    }

    #[test]
    fn uses_stable_mcp_labels() -> Result<(), AnswerFormatError> {
        let mut input = input(ValidationStatus::Valid);
        input.target = FormatTarget::Mcp;

        let output = format_answer(input)?;

        assert_eq!(output.source_cards[0].label, "source:1");
        assert_eq!(output.graph_cards[0].label, "graph:1");
        Ok(())
    }

    #[test]
    fn rejects_missing_answer_text() {
        let mut input = input(ValidationStatus::Valid);
        input.raw_answer = "  ".to_string();

        assert_eq!(format_answer(input), Err(AnswerFormatError::MissingAnswer));
    }

    #[test]
    fn rejects_missing_trace_id() {
        let mut input = input(ValidationStatus::Valid);
        input.trace_id = "  ".to_string();

        assert_eq!(format_answer(input), Err(AnswerFormatError::MissingTraceId));
    }

    #[test]
    fn formats_error_messages() {
        assert_eq!(
            AnswerFormatError::MissingAnswer.to_string(),
            "missing answer text"
        );
        assert_eq!(
            AnswerFormatError::MissingTraceId.to_string(),
            "missing trace id"
        );
    }
}
